common/models/Category.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "category".
 *
 * @property integer $id
 * @property string $icon
 * @property string $title
 * @property string $account_id
 * @property integer $status
 */
class Category extends \yii\db\ActiveRecord
{
    const STATUS_ACTIVE = 1;
    const STATUS_DISACTIVE = 0;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'account_id'], 'required'],
            [['status', 'account_id'], 'integer'],
            [['icon', 'title'], 'string', 'max' => 255],
            [['is_deleted'],"boolean"],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'icon' => Yii::t('app', 'Icon'),
            'title' => Yii::t('app', 'Title'),
            'account_id' => Yii::t('app', 'Account ID'),
            'status' => Yii::t('app', 'Status'),
        ];
    }

//    public function beforeDelete()
//    {
//        $toCategory = Operation::find()->where(['to_type' => 'category'])->andWhere(['to_id' => $this->id])->all();
//
//        foreach ($toCategory as $category){
//            $category->to_id = null;
//            $category->save(false);
//        }
//
//        return true;
//    }
}

frontend/controllers/CategoryController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Category;
use common\models\CategorySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\UserAccount;
use yii\helpers\ArrayHelper;

/**
 * CategoryController implements the CRUD actions for Category model.
 */
class CategoryController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

//    public function beforeAction($action)
//    {
//        if (Yii::$app->user->isGuest) {
//            return $this->redirect(['/user/login'])->send();
//        } else {
//            parent::beforeAction($action);
//        }
//    }

    /**
     * Lists all Category models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['/user/login']);
        }
        $searchModel = new CategorySearch();
        $request = ArrayHelper::merge(Yii::$app->request->queryParams, ['CategorySearch' => ['account_id' => UserAccount::getFinId(),'is_deleted'=> false]]);
        $dataProvider = $searchModel->search($request);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Category model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['/user/login']);
        }
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Category model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['/user/login']);
        }
        $model = new Category();
        $model->account_id = UserAccount::getFinId();
        $model->status = 1;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Category model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['/user/login']);
        }
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Category model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->is_deleted = true;
        $model->save();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Category model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Category the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Category::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionArchive($id){
        $category = Category::findOne($id);
        $category->status = $category->status==Category::STATUS_ACTIVE
            ? Category::STATUS_DISACTIVE
            : Category::STATUS_ACTIVE;
        $category->save();

        return $this->redirect(['index']);
    }

    public function actionDeleteMultiple(){
        if(isset($_REQUEST['selection'])){
            foreach (Yii::$app->request->post('selection') as $select){
                $card = Category::findOne($select);
                $card->is_deleted = true;
                $card->save();
            }
            Yii::$app->session->setFlash('success', "Categories were successfully removed!");
        }

        return $this->redirect(Yii::$app->request->referrer);
    }
}

frontend/views/category/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Category */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="row">
    <div class="col-md-12">
        <div class="box box-success">
            <div class="box-body">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
                
            </div>
        </div>
    </div>
</div>

frontend/views/category/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\CategorySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="category-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'icon') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'account_id') ?>

    <?= $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/category/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Category */

$this->title = Yii::t('app', 'Create Category');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Categories'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="category-create">

<!--    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><?= Html::encode($this->title) ?></h1>
        </div>
         /.col-lg-12
    </div>-->

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/category/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\helpers\Url;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\CategorySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Categories');
$this->params['breadcrumbs'][] = $this->title;
$this->registerCssFile('/css/input.css');

?>
<div class="row">
    <div class="col-md-12">
        <div class="box box-success">
            <div class="box-body mobile-friendly-table">
                <div id="mult-del" style="margin-bottom: 20px; float: right">
                    <button style="background-color: #ff4081!important" id="submit-delete" class="btn btn-info">Delete multiple</button>
                </div>
                <p>
                    <?= Html::a("<i class='fa fa-plus'></i> ".Yii::t('app', 'Create Category'), ['create'], ['class' => 'btn btn-success']) ?>
                </p>
                <?php Pjax::begin(); ?>
                <?=Html::beginForm(['category/delete-multiple'],'post', ['id' => 'form-statistic']);?>
                <?= GridView::widget([
                    'dataProvider' => $dataProvider,
                    'columns' => [
                        [
                            'class' => 'yii\grid\SerialColumn',
                            'contentOptions' => ['data-title' => '#'],
                        ],
                        [
                            'attribute' => 'title',
                            'contentOptions' => ['data-title' => 'Category'],
                        ],
                        [
                            'attribute' => 'status',
                            'value'=> function($data){
                                return $data->status?Yii::t('app', 'Active'):Yii::t('app', 'Not active');
                            },
                            'contentOptions' => ['data-title' => 'Status'],
                        ],
                        [
                            'class' => 'yii\grid\ActionColumn',
                            'template' => '{update}&nbsp;&nbsp;{delete}&nbsp;&nbsp;{archive}',
                            'buttons'=> [
                                'archive'=>function($url, $model, $key){
                                    return $model->status
                                        ? Html::a('<span class="glyphicon glyphicon-floppy-remove"></span>',
                                            Url::to(['/category/archive', 'id'=>$model->id]),
                                            ['title' => Yii::t('app', 'Disactivate')])
                                        : Html::a('<span class="glyphicon glyphicon-floppy-saved"></span>',
                                            Url::to(['/category/archive', 'id'=>$model->id]),
                                            ['title' => Yii::t('app', 'Disactivate')]);
                                }
                            ]
                        ],
                        ['class' => 'yii\grid\CheckboxColumn',
                            'header' => Html::checkBox('selection_all', false, [
                                'class' => 'select-on-check-all',
                                'label' => 'Check All',
                            ]),
                            'checkboxOptions' => function($model) {
                                return ['value' => $model->id, 'class' => 'filled-in'];
                            },
                        ],
                    ],
                ]); ?>
                <?php Pjax::end(); ?>
                <?= Html::endForm();?>
            </div>
        </div>
    </div>
</div>

frontend/views/category/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Category */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Category',
]) . $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Categories'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="category-update">

<!--    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><?= Html::encode($this->title) ?></h1>
        </div>
         /.col-lg-12
    </div>-->

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/category/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Category */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Categories'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="category-view">

    <!--<h1><?= Html::encode($this->title) ?></h1>-->

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'icon',
            'title',
            'account_id',
            'status',
        ],
    ]) ?>

</div>