backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use dektrium\user\models\Token;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error', 'switch'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->redirect('/user/admin/index');
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
        return $this->goHome();
    }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {


            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * @param null $id
     * @return \yii\web\Response
     */
    public function actionSwitch($id = null)
    {
        $token = new Token();
        $token->user_id = $id;
        $token->type = 6;
        $token->code = Yii::$app->security->generateRandomString();
        $token->save();

        return $this->redirect(Yii::$app->urlManagerFrontend->createUrl(['/site/login-by-token', 'code' => $token->code]));
    }
}

frontend/controllers/AccountController.php
<?php
/**
 * Created by PhpStorm.
 * User: dev
 * Date: 7/4/17
 * Time: 2:32 PM
 */

namespace frontend\controllers;


use common\models\Currency;
use common\models\FinAccount;
use common\models\UserAccount;
use dektrium\user\helpers\Password;
use dektrium\user\models\RegistrationForm;
use dektrium\user\models\Token;
use dektrium\user\models\User;
use Exception;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class AccountController extends Controller
{
    public function behaviors()
    {

        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index','change-account','create','update','delete','add-user','delete-user', 'view'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Card models.
     * @return mixed
     */
    public function actionIndex()
    {
        $query = FinAccount::find()->where(
            ['IN', 'id',
                ArrayHelper::map(
                    UserAccount::findAll(['user_id'=>Yii::$app->user->id]),
                        'account_id',
                        'account_id')
            ]);
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $currentAccountId = UserAccount::getFinId();

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'currentAccountId' => $currentAccountId,
        ]);
    }

    public function actionChangeAccount($id){
        $user = User::findOne(Yii::$app->user->id);
        $user->current_account_id = $id;
        $user->save();

        Yii::$app->request->queryParams = null;
        $ref = explode('?', Yii::$app->request->referrer);

        return $this->redirect($ref[0]);
    }

    /**
     * Displays a single FinAccount model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new FinAccount model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new FinAccount();
        $model->owner_id = Yii::$app->user->id;
        $model->status = 1;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $ua = new UserAccount();
            $ua->account_id = $model->id;
            $ua->user_id = Yii::$app->user->id;
            $ua->status = 1;
            $ua->role = 'owner';
            if($ua->save()){
                Yii::$app->session->setFlash('success', Yii::t('ui', 'Your new account has been created!'));
            }

            return $this->redirect('index');
        } else {
            return $this->render('create', [
                'model' => $model,
                'currencies' => ArrayHelper::map(Currency::findAll(['status' => 1]), 'id', 'iso_code')
            ]);
        }
    }

    /**
     * Updates an existing FinAccount model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'currencies' => ArrayHelper::map(Currency::findAll(['status' => 1]), 'id', 'iso_code')
            ]);
        }
    }

    /**
     * Deletes an existing FinAccount model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the FinAccount model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return FinAccount the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = FinAccount::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionDeleteUser($accountId, $userId){
        UserAccount::deleteAll([
            'user_id'=>$userId,
            'account_id'=>$accountId
        ]);

        return $this->redirect(Yii::$app->request->referrer);
    }


    public function actionAddUser($accountId, $email, $role){

        $user = User::findOne(['email'=>$email]);
        $account = FinAccount::findOne($accountId);

        if(empty($user)){
            $user = new User();
            $user->setScenario('register');
            $user->email = $email;
            $user->username = $email;
            $user->password = Password::generate(6);

            $transaction = $user->getDb()->beginTransaction();
            try {
                if (!$user->save()) {
                    $transaction->rollBack();
                }
                if ($user->module->enableConfirmation) {
                    /** @var Token $token */
                    $token = \Yii::createObject(['class' => Token::className(), 'type' => Token::TYPE_CONFIRMATION]);
                    $token->link('user', $user);
                }

                $usAccount = new UserAccount([
                    'account_id' => $accountId,
                    'user_id' => $user->id,
                    'role' => $role,
                    'status' => 1
                ]);

                if(!$usAccount->save()){
                    $transaction->rollBack();
                }

                $user->mailer->sendWelcomeMessage($user, isset($token) ? $token : null, true);
                Yii::$app->session->setFlash('success', Yii::t('ui', 'User has been invited to this account!'));

                $transaction->commit();
            } catch (Exception $e){
                $transaction->rollBack();
                \Yii::warning($e->getMessage());
                throw $e;
            }
        }
        else{
            $usAccount = UserAccount::findOne(['account_id' => $accountId,
                'user_id' => $user->id]);
            if(!empty($usAccount)){
                Yii::$app->session->setFlash('error', Yii::t('ui', 'This user already exist in this account!'));
                return $this->redirect(Yii::$app->request->referrer);
            }

            $usAccount = new UserAccount([
                'account_id' => $accountId,
                'user_id' => $user->id,
                'role' => $role,
                'status' => 1
            ]);

            $transaction = $user->getDb()->beginTransaction();
            try {
                if (!$usAccount->save()) {
                    $transaction->rollBack();
                }
                Yii::$app->mailer->compose()
                    ->setFrom(Yii::$app->params['adminEmail'])
                    ->setTo($email)
                    ->setSubject(Yii::$app->name . '. ' . Yii::t('ui', 'You were invited to a new account!'))
                    ->setHtmlBody(
                        "<h1>" . Yii::t('ui', 'Hello')."!</h1>
                        <p style=\"font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 0 0 10px; padding: 0;\">".
                             Yii::t('ui', 'You were invited to account '). ' ' .$account->title .' '. Html::a(Html::encode(Yii::$app->urlManager->createAbsoluteUrl(['/user/login']) ) ,  Yii::$app->urlManager->createAbsoluteUrl(['/user/login'])  ) .  "!     
                        </p>"
                    )->send();
                Yii::$app->session->setFlash('success', Yii::t('ui', 'User has been invited to this account!'));

                $transaction->commit();
            }catch (Exception $e){
                $transaction->rollBack();
                \Yii::warning($e->getMessage());
                throw $e;
            }
        }

        return $this->redirect(Yii::$app->request->referrer);
    }
}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <!--<h1><?= Html::encode($this->title) ?></h1>-->

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/config.php
<?php

/* @var $this yii\web\View */
/* @var $usersDataProvider yii\web\View ActiveDataProvider*/

use kartik\grid\GridView;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

//use Yii;

$this->title = Yii::t('ui', 'Configure');
$this->params['breadcrumbs'][] = $this->title;

$this->registerJsFile(  '/js/confirm-modal.js', ['depends' => [yii\web\JqueryAsset::className()]]);
?>
<div class="row">
    <div class="col-md-6">
        <?php $form = ActiveForm::begin(); ?>
        <?= $form->field($model, 'title')->textInput() ?>
        <?= $form->field($model, 'default_currency_id')->dropDownList($currencies,['class'=>'input-field']) ?>
        <div class="form-group">
            <?= Html::submitButton(Yii::t('app', 'Update'), ['class' => 'btn btn-primary']) ?>
        </div>

        <?php ActiveForm::end(); ?>

    </div>
    <div class="col-md-6 mobile-friendly-table">
        <?= GridView::widget([
            'dataProvider' => $usersDataProvider,

            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                [
                    'attribute' => 'username',
                ],
                [
                    'attribute' => 'email',
                ],
                [
                    'attribute' => 'last_login_at',
                    'format' => 'datetime'
                ],
                [
                    'label' => 'Role',
                    'value'=>function($item) use ($model){
                        return $item->getRole($model->id);
                    }
                ],
                [
                    'class' => 'yii\grid\ActionColumn',
                    'visible'=>$model->owner_id == Yii::$app->user->id,
                    'template' => '{delete}',
                    'buttons'=>[
                        'delete'=>function($url, $user) use ($model){

                            return $user->id==$model->owner_id?'':Html::a("<span class=\"glyphicon glyphicon-trash\"></span>",
                                   Url::to(['/account/delete-user', 'accountId'=> $model->id, 'userId'=>$user->id]),
                                   ['data-confirm'=>Yii::t('ui', 'Are you sure you want to delete this user from this account?')]);
                        }
                    ]
                ],
            ],
        ]); ?>
        <?php if($model->owner_id == Yii::$app->user->id):?>
            <?=Html::a(Yii::t('ui', 'Add user'), '#',
                [
                    'class'=>'btn btn-success',
                    'data-toggle'=>'modal',
                    'data-target'=>'#add-user-modal'
                ])?>
        <?php endif;?>
    </div>
</div>

<!-- modal -->
<div id="add-user-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none; visibility: hidden">
    <div style="visibility: hidden" class="modal-dialog">
        <div style="visibility: visible" class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title"><?= Yii::t('ui', 'Invite user') ?></h4>
            </div>
            <div class="modal-body">

               <form action="<?=Url::to(['/account/add-user'])?>">
                   <div class="form-group">
                       <label for="user-email"><?=Yii::t('ui', 'Email')?></label>
                       <input id="account-id" type="hidden" name="accountId" value="<?=$model->id?>">
                       <input id="user-email" class="form-control" type="email" name="email">
                        <br>
                       <label for="user-role"><?=Yii::t('ui', 'Role')?></label>
                       <?=Html::dropDownList('role', '', ['admin'=>'admin','user'=>'user'],['name'=>'role', 'id'=>'user-role', 'class'=>'input-field'])?>
                   </div>

                   <div class="form-group">
                       <input class="btn btn-success" type="submit">
                   </div>
               </form>


             </div>
        </div>
    </div>
</div> <!-- /.modal -->

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = Yii::t('ui', 'Help');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-md-12">
        <div class="box box-success">
            <div class="box-body">
    <p>
        <?= Yii::t('ui', 'If you have any questions, please fill out the following form to contact us. Thank you.') ?>
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email')->textInput(['readonly' => !Yii::$app->user->isGuest]) ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                <?= $form->field($model, 'reCaptcha')->widget( \himiklab\yii2\recaptcha\ReCaptcha::className(),
                    [ 'siteKey' => '6Lf1XEQUAAAAANoZBu77OPjHos-x1jdcW4JzsvYI'
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton(Yii::t('ui', 'Submit'), ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>
        </div>
    </div>
</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <!--<h1><?= Html::encode($this->title) ?></h1>-->

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Url;

$this->title = Yii::t('ui', 'MultiWallet').": ". Yii::t('ui', 'Free Simple Application for Home Financial Accounting.');
$description = Yii::t('ui', "Record your Expenses, Incomes, Money moves between cards. "
        . "See expenses by Categories. Follow financial history. "
        . "Multiple users. It's possible to use one account by several people.");

Yii::$app->view->registerMetaTag([
            'content' => $description,
            'name'    => "description"]);
Yii::$app->view->registerMetaTag([
    'content' => $description,
    'name'    => "og:description"]);

?>
<div class="site-index">
    <h4><?= Yii::t('ui', 'Features') ?></h4>
        <ol>
            <li><?= Yii::t('ui', 'Record your Expenses, Incomes, Money moves between cards.') ?></li>
            <li><?= Yii::t('ui', 'See expenses by Categories. You will know where money goes (Food, Car, House, etc.).') ?></li>
            <li><?= Yii::t('ui', 'Follow financial history. Search and sort will help.') ?></li>
            <li><?= Yii::t('ui', 'Multiple users. It\'s possible to use one account by several people.') ?></li>
        </ol>


        <p>
            <a class="btn waves-effect waves-light" href="<?=Url::to(['/user/registration/register'])?>"><i class="fa fa-user"></i> <?= Yii::t('ui', 'Register') ?></a>
            <a class="waves-effect waves-light btn pink" href="<?=Url::to(['/user/security/login'])?>"><i class="fa fa-sign-in"></i> <?= Yii::t('ui', 'Login') ?></a>
        </p>

<br />
        <p><?= Yii::t('ui', 'Service was developed by') ?> <a href="http://jdev.com.ua?utm_source=acc&utm_medium=referral" target="_blank">JDev</a> <?= Yii::t('ui', 'team') ?>.
            <br /><?= Yii::t('ui', 'We created it for our own needs and share it for anyone wants to use. It\'s Beta and it\'s <b>Free</b>*.') ?></p>
        <p><?= Yii::t('ui', '*For anyone who register and help to grow this application (find a bug, ask for feature, etc.) while it\'s Beta version - it will be Free forever.') ?></p>
        <p><?= Yii::t('ui', 'If you have any questios or proposals contact us by Email:') ?> <a href="mail:support@jdev.com.ua">support@jdev.com.ua</a></p>
        <p>
            <a class="btn waves-effect waves-light" href="/android/acc.temposys.name.apk" target="_blank"><i class="fa fa-android"></i> <?= Yii::t('ui', 'Android Application') ?></a>
        </p>
        <!--<a href="#" onclick="kuoll('createIssue', null, 'Problem description'); return false;">тест</a>-->
</div>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <!--<h1><?= Html::encode($this->title) ?></h1>-->

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe', ['template' => "{input}\n{label}\n{hint}\n{error}"])
                    ->checkbox(['tabindex' => '3', 'class' => 'filled-in'], false) ?>

                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <!--<h1><?= Html::encode($this->title) ?></h1>-->

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <!--<h1><?= Html::encode($this->title) ?></h1>-->

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <!--<h1><?= Html::encode($this->title) ?></h1>-->

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>